openapi: "3.0.1"
info:
  title: Coffee Shop APIs
  description: This is open API specification for Coffee Shop
  version: v1
servers:
  - url: coffee-shop/api
paths:
  /v1/menu:
    get:
      summary: Returns the menu.
      description: Get menu.
      tags:
        - Menu
      responses:
        '200':    # status code
          description: Menu returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuInfo'
  /v1/order:
    post:
      summary: Place an order from menu.
      description: Place an order from menu.
      tags:
        - Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '201':    # status code
          description: Order placed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderInfo'
components:
  schemas:
    MenuInfo:
      type: object
      properties:
        menuDetails:
          type: array
          items:
            $ref: '#/components/schemas/MenuDetail'
    MenuDetail:
      type: object
      properties:
        menuId:
          type: string
        menuName:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        menuItems:
          type: array
          items:
            $ref: '#/components/schemas/MenuItem'
    MenuItem:
      type: object
      properties:
        menuItemId:
          type: string
        menuItemName:
          type: string
        quantity:
          type: integer
        price:
          type: integer
        category:
          type: string
          enum:
            - 'frozenChocolate'
            - 'classic'
            - 'teaChiller'
            - 'coffeeChiller'
            - 'italianSoda'
    OrderRequest:
      type: object
      required: [customerId, menuItems]
      properties:
        customerId:
          type: string
        menuItems:
          type: array
          items:
            $ref: '#/components/schemas/MenuItemRequest'
    MenuItemRequest:
      type: object
      required: [menuItemId, quantity]
      properties:
        menuItemId:
          type: integer
        quantity:
          type: integer
          minimum: 1
    OrderInfo:
      type: object
      properties:
        customerId:
          type: string
        orderId:
          type: integer
        status:
          type: string
          enum:
            - 'placed'
            - 'preparing'
            - 'delivered'
            - 'cancelled'